# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_title', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('item_desc', models.CharField(max_length=100)),
                ('item_image', models.FileField(upload_to='')),
                ('item_time_add', models.DateTimeField()),
                ('item_time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Sales'),
        ),
    ]
