# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-28 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amt', models.IntegerField()),
                ('bid_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_title', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('item_desc', models.CharField(max_length=100)),
                ('item_image', models.FileField(upload_to='')),
                ('item_time_add', models.DateTimeField()),
                ('item_date_end', models.DateField()),
                ('item_time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Sales'),
        ),
        migrations.AddField(
            model_name='items',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Items'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
