# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_tim_end',
            new_name='item_time_end',
        ),
    ]
