# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20160825_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_item',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_item',
            field=models.ManyToManyField(to='auctions.Items'),
        ),
    ]
