# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
