# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20160825_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_item',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.Items'),
            preserve_default=False,
        ),
    ]
