# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20160802_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.FileField(upload_to=''),
        ),
    ]
