# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20160802_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
